version: '3'

services:
  todolistwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  todolistservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

