version: '3'

services:
  todolistwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Jarito
    ports:
      - "443:443"

  todolistservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Jarito
    ports:
      - "80"

