version: '3'

services:
  todolistwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "80:9090"

  todolistservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "81:9091"

